### ISSUE TITLE
[duplication] When multiple smelting is enabled

### ISSUE THREAD

**Issue by kreezxil** [Commoble/jumbo-furnace#3] opened 2020-09-22 20:54 UTC
I have multiple smelting enabled. And for the most part this works as intended. But when clay balls are put in, a stack of 16 will produce 9 stacks of 64.

My config:
```toml
["Cooking Settings"]
	#Maximum recipes the Jumbo Furnace is able to process simultaneously
	#Range: > 1
	max_simultaneous_recipes = 9
	#Cook Time
	#Range: > 1
	cooktime = 100
```

https://youtu.be/atH_Mjc_dIU

Version: 1.15.2-1.0.0.2
Forge: 1.15.2-31.2.41

**Comment by kreezxil** [comment] 2020-09-22 20:57
Just tried it a log, no such luck, something funky about the clay balls it seems. Great for minecolonies and anything that needs bricks tho!

**Comment by Commoble** [comment] 2020-09-29 20:29
Doesn't reproduce for me. Is another mod or datapack present that changes the clay ball -> brick smelting recipe or adds another one?

**Comment by kreezxil** [comment] 2020-09-30 12:43
did you try my config?

**Comment by Commoble** [comment] 2020-09-30 15:59
Yes, I pasted your config as-is into the serverconfig when I tried to reproduce it

**Comment by kreezxil** [comment] 2020-10-01 12:47
hmmm

**Comment by Commoble** [comment] 2020-11-17 17:32
Closing due to being unable to reproduce + multismelt was reworked in 1.16

**Closed by Commoble** 2020-11-17 17:32 UTC
